logging:
  level:
    org.springframework: ERROR
    io.github.coenraadhuman.gib: DEBUG
    io.github.coenraadhuman.gib.cli: DEBUG
    io.github.coenraadhuman.gib.command: DEBUG
  pattern:
    console: "%green(%level) %msg%n"

spring:
  main:
    banner-mode: "off"